### ISSUE TITLE
Nextcloud compatibility

### ISSUE THREAD

**Issue by gusarg81** [owncloud/pyocclient#206] opened 2017-09-11 12:27 UTC
Hi,

    I would like to know if I can use it with Nextcloud. Thanks.

EDIT: well, I've tested the basic example and just works :)

**Comment by PVince81** [comment] 2017-09-11 14:51
Closing as duplicate of https://github.com/owncloud/pyocclient/issues/189.

Since the APIs are similar / the same, it will likely work.

**Closed by PVince81** 2017-09-11 14:51 UTC
