### ISSUE TITLE
It's not possible to upload files to OC 6.0.9 with encryption enabled

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/pyocclient#106] opened 2015-08-05 12:33 UTC
Sample code:
```
import owncloud
oc = owncloud.Client('http://.........')
oc.login('user','password')
oc.put_file('/qwerty.txt', 'upload_this.txt')
```

Also tried setting the "single_session" flag as False, with the same result.

Without encryption enabled it works fine

Upload from the web interface, through cadaver and curl (cli) and directly with the python requests module work fine
```
import requests
requests.put('http://........./remote.php/webdav/foo2.txt', data=open('000.txt').read(), auth=('user', 'password'))
```

**Comment by PVince81** [comment] 2015-08-05 12:50
Any error message ?

**Comment by jvillafanez** [comment] 2015-08-05 12:58
```
>>> oc.put_file('qwerty.txt', 's.conf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jvillafanez/.virtualenvs/upgrade-script2/src/pyocclient/owncloud/owncloud.py", line 363, in put_file
    **kwargs
  File "/home/jvillafanez/.virtualenvs/upgrade-script2/src/pyocclient/owncloud/owncloud.py", line 473, in __put_file_chunked
    headers=headers
  File "/home/jvillafanez/.virtualenvs/upgrade-script2/src/pyocclient/owncloud/owncloud.py", line 1300, in __make_dav_request
    raise ResponseError(res)
owncloud.owncloud.ResponseError: HTTP error: 403
```

No log messages in the ownCloud log

**Comment by PVince81** [comment] 2015-08-05 13:03
I'm able to reproduce this too.
Very strange!

**Comment by PVince81** [comment] 2015-08-05 13:08
Ok it looks like there is no private key in the session.

pyocclient authenticates by connecting to index.php and saving the cookie.
For some reason that cookie doesn't contain the proper session so isn't linked with the encryption session. Also I remember that the server might return several cookies and maybe it picks the wrong one.

That should normally work with single_session but seems it doesn't.

**Comment by PVince81** [comment] 2015-08-05 13:26
Looks like clearing the cookies between requests fixes the issue because it forces re-auth.
It looks like OC 6 doesn't always reauth if both credentials + session cookies are passed. (@LukasReschke can you confirm ?)

I have a working POC that clears cookies when single_session=False, will push soon.

**Comment by PVince81** [comment] 2015-08-05 13:31
There was a similar issue with the mobile clients, not sure how it was fixed and whether there is also a workaround for OC 6 + encryption there ? @rperezb do you remember ?

**Comment by rperezb** [comment] 2015-08-05 14:43
@PVince81 on this issue https://github.com/owncloud/ios/issues/246 they are pointing to: https://github.com/owncloud/core/pull/13496#issuecomment-73067432

**Comment by nickvergessen** [comment] 2015-10-08 06:33
OC6 has reached end of support?

**Comment by PVince81** [comment] 2015-10-08 08:22
I'm not really happy with the hack, so would be glad to discard the PR when OC6 is out of support.

**Comment by nickvergessen** [comment] 2015-10-08 08:30
https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

         | release date   | end of life | current version       | next version
:-------:|---------------:|------------:|----------------------:|---------------------:
**6.0**  | 2013-12-11     | 2015-09     | 6.0.9 (2015-07-07)    | **End of Life**

**Comment by PVince81** [comment] 2015-10-08 08:31
Thanks, closing

**Closed by PVince81** 2015-10-08 08:31 UTC
Labels: bug
